//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.CODIGO_ARTICULO = new HashSet<CODIGO_ARTICULO>();
            this.IMPUESTO_ARTICULO = new HashSet<IMPUESTO_ARTICULO>();
            this.VENTA_DETALLE = new HashSet<VENTA_DETALLE>();
        }
    
        public int ID_ARTICULO { get; set; }
        public int ID_LINEA { get; set; }
        public int ID_ESTATUS_ARTICULO { get; set; }
        public int ID_UNIDAD_MEDIDA { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string FABRICANTE { get; set; }
        public string IMAGEN { get; set; }
        public int TIENE_CADUCIDAD { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODIGO_ARTICULO> CODIGO_ARTICULO { get; set; }
        public virtual ESTATUS_ARTICULO ESTATUS_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPUESTO_ARTICULO> IMPUESTO_ARTICULO { get; set; }
        public virtual LINEA LINEA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE> VENTA_DETALLE { get; set; }
    }
}
