//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public int ID_CAJA { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
