//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODIGO_ARTICULO
    {
        public int ID_CODIGO_ARTICULO { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<bool> PRINCIPAL { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
