//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_VENTAEntities : DbContext
    {
        public BD_VENTAEntities()
            : base("name=BD_VENTAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALMACEN> ALMACEN { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<CAJA> CAJA { get; set; }
        public virtual DbSet<CODIGO_ARTICULO> CODIGO_ARTICULO { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<ESTATUS_ARTICULO> ESTATUS_ARTICULO { get; set; }
        public virtual DbSet<IMPUESTO_ARTICULO> IMPUESTO_ARTICULO { get; set; }
        public virtual DbSet<LINEA> LINEA { get; set; }
        public virtual DbSet<OFERTA_CLIENTE_SUCURSAL> OFERTA_CLIENTE_SUCURSAL { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public virtual DbSet<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        public virtual DbSet<COMPANIA> COMPANIA { get; set; }
    }
}
