//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCURSAL()
        {
            this.ALMACEN = new HashSet<ALMACEN>();
            this.ARTICULO = new HashSet<ARTICULO>();
            this.CAJA = new HashSet<CAJA>();
            this.OFERTA_CLIENTE_SUCURSAL = new HashSet<OFERTA_CLIENTE_SUCURSAL>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public int ID_SUCURSAL { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string NUMERO_EXTERIOR { get; set; }
        public string NUMERO_INTERIOR { get; set; }
        public string COLONIA { get; set; }
        public string MUNICIPIO { get; set; }
        public string ESTADO { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string TELEFONO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int ID_USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public int ID_USUARIO_ACTUALIZACION { get; set; }
        public int ID_COMPANIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALMACEN> ALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAJA> CAJA { get; set; }
        public virtual CUENTA CUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFERTA_CLIENTE_SUCURSAL> OFERTA_CLIENTE_SUCURSAL { get; set; }
        public virtual COMPANIA COMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
