//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_DETALLE
    {
        public int ID_VENTA_DETALLE { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<decimal> PRECIO_ARTICULO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal TOTAL { get; set; }
        public int ID_OFERTA_CLIENTE { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
